name       : python-zope.hookable
version    : 5.1.0
release    : 7
source     :
    - https://github.com/zopefoundation/zope.hookable/archive/refs/tags/5.1.0.tar.gz : cddd85df329aa183b3856c23a63b65f24067f084d7947156f2699c7c7f11040e
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope hookable architecture
description: |
    This package supports the efficient creation of "hookable" objects, which are callable objects that are meant to be optionally replaced.

    The idea is that you create a function that does some default thing and make it hookable. Later, someone can modify what it does by calling its sethook method and changing its implementation. All users of the function, including those that imported it, will see the change
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
