name       : python-zope.hookable
version    : 5.0.1
release    : 5
source     :
    - https://github.com/zopefoundation/zope.hookable/archive/refs/tags/5.0.1.tar.gz : 10b0b9575a4c682521ba0bae588c94cfe5d0cd1bfb121bf6cd9be69a19703df8
license    : ZPL-2.1
component  : programming.python
summary    : Represents the core of the Zope hookable architecture
description: |
    This package supports the efficient creation of "hookable" objects, which are callable objects that are meant to be optionally replaced.

    The idea is that you create a function that does some default thing and make it hookable. Later, someone can modify what it does by calling its sethook method and changing its implementation. All users of the function, including those that imported it, will see the change
builddeps  :
    - pkgconfig(python3)
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
